basePath: /
definitions:
  api.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  api.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  api.Ok:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  api.PostRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  api.RegisterRequest:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - first_name
    - last_name
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Blog application
  title: Blog API
  version: 0.0.1
paths:
  /api/posts:
    get:
      consumes:
      - application/json
      description: get all posts
      operationId: get all posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Ok'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/api.Error'
      summary: Get All Posts
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: create post
      operationId: create post
      parameters:
      - description: post info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.PostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Ok'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/api.Error'
      summary: Create Post
      tags:
      - posts
  /api/posts/:id:
    delete:
      consumes:
      - application/json
      description: delete post
      operationId: delete post
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Ok'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/api.Error'
      summary: Delete Post
      tags:
      - posts
    get:
      consumes:
      - application/json
      description: get post by id
      operationId: get post by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Ok'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/api.Error'
      summary: Get Post by ID
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: update post
      operationId: update post
      parameters:
      - description: post info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.PostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Ok'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/api.Error'
      summary: Update Post
      tags:
      - posts
  /auth/login:
    post:
      consumes:
      - application/json
      description: login user
      operationId: login user
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/api.Error'
      summary: SignIn
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: create user
      operationId: create user
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.RegisterRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/api.Error'
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
